import type { Metadata } from "next";

import "./globals.css";
import Home from "../components/count";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <>
          <Home></Home>
          {children}
        </>
      </body>
    </html>
  );
}
